project/apps/users/urls.py
from django.urls import path
from project.apps.users import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register')
]

project/urls.py
from django.urls import path, include
from django.contrib.auth.models import User
from project.apps.users import views
# from rest_framework import routers, serializers, viewsets

# # Serializers define the API representation.


# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = ('url', 'username', 'email', 'is_staff')

# # ViewSets define the view behavior.


# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer


# # Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    # url(r'^', include(router.urls)),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', views.index, name='home'),
    path('user/', include(('project.apps.users.urls', 'user'), namespace='user')),
]

project/apps/users/models.py
from mongoengine import *

connect('DB', username='xmzd', password='1234')


class Users(Document):
    account = StringField(required=True)
    password = StringField(required=True)

    @classmethod
    def create(cls, account, pwd):
        return cls(account=account, password=pwd).save()

    @classmethod
    def get_by_id(cls, uid):
        return cls.objects.with_id(uid)

    @classmethod
    def get_by_email(cls, email):
        try:
            return cls.objects.get(account=email)
        except DoesNotExist:
            return None


















# from django.db import models
# from datetime import datetime
#
# # Create your models here.
#
#
# class BookInfo(models.Model):
#     # 图书名称
#     btitle = models.CharField(max_length=20)
#     # 阅读量
#     bread = models.IntegerField(default=0)
#     # 评论量
#     bcomment = models.IntegerField(default=0)
#     # 删除标记
#     isDelete = models.BooleanField(default=False)
#
#     # 让模型类生成的 表名 不依赖 应用名(project/apps/users)
#     class Meta:
#         db_table = 'book'
#
#
# class HeroInfo(models.Model):
#     # 英雄名
#     hname = models.CharField(max_length=20)
#     # 性别
#     hgender = models.BooleanField(default=False)
#     # 备注
#     hcomment = models.CharField(max_length=200)
#     # 关系属性
#     hbook = models.ForeignKey('BookInfo', id)
#     # 删除标记
#     isDelete = models.BooleanField(default=False)
#
#     class Meta:
#         db_table = 'hero'

project/apps/users/views.py
# from bson.objectid import ObjectId
# from django import forms
# from django.conf import settings
# from django.contrib.auth import authenticate, logout
# from django.contrib.auth.hashers import check_password, make_password
# from django.contrib.auth.mixins import LoginRequiredMixin
# from django.core.mail import send_mail
# from django.http import HttpRequest, HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from project.apps.users.models import Users


# Create your views here.

def index(request):
    return redirect('/user/login/')

def login(request):
    if request.method == 'GET':
        pass
    return render(request, 'users/login.html')

def register(request):
    if request.method == 'POST':
        account = request.POST.get('account')
        password = request.POST.get('password')
        Users.create(account, password)
        if Users.get_by_email(account):
            return redirect('/user/login/')
    return render(request, 'users/register.html')

project/templates/users/_base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>

<head>
<<<<<<< HEAD
    <meta charset="UTF-8">
    {# 移动设备 #}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
        <title>Index</title>
    {% endblock %}

    <!-- 新 Bootstrap4 核心 CSS 文件 -->
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/base.css' %}">
    {% block _css %}
    {% endblock %}
=======
  <meta charset="UTF-8">
  {# 移动设备 #}
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Index</title>

  <!-- 新 Bootstrap4 核心 CSS 文件 -->
  <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/css/bootstrap-grid.min.css' %}">
  {% block _css %}
  {% endblock %}
>>>>>>> 8169ea1db3dfb32cf12f89e49b17c49351d4429e

  <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
  <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
  <!-- popper.min.js 用于弹窗、提示、下拉菜单 -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
  <!-- 最新的 Bootstrap4 核心 JavaScript 文件 -->
  <script src="{% static '/js/bootstrap.min.js' %}"></script>

  {% block _js %}
  {% endblock %}
</head>

<body>
<<<<<<< HEAD
<main class="bg-body">
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <div class="container-fluid">
        {% block main-body %}
        {% endblock %}
    </div>
</main>
=======
  <main class="main-container bg-dark">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <div class="container-fluid bg-dark">
      {% block main-body %}
      <h5 class="text-danger">hello world</h5>
      {% endblock %}
    </div>
  </main>
>>>>>>> 8169ea1db3dfb32cf12f89e49b17c49351d4429e
</body>

</html>

project/templates/users/login.html
{% extends "users/_base.html" %}
{% load staticfiles %}

{% block main-body %}
    <div class="bg-info">
        <img src="{% static 'image/bg.jpg' %}" alt="">
    </div>
    <h3>简单的导航栏实例</h3>
  <p>导航栏一般放在页面的顶部。</p>
  <p>我们可以使用 .navbar 类来创建一个标准的导航栏，后面紧跟: .navbar-expand-xl|lg|md|sm 类来创建响应式的导航栏 (大屏幕水平铺开，小屏幕垂直堆叠)。</p>
{% endblock %}

project/templates/users/register.html
{% extends "users/_base.html" %}
{% load staticfiles %}

{% block title %}
    <title>注册...</title>
{% endblock %}

{% block main-body %}
    <div class="container justify-content-center col-4">
        <form action="{% url 'user:register' %}" method="post">
            {% csrf_token %}
            <div class="form-group icon m-3 text-center">
                <img src="{% static '/image/icon.jpeg' %}">
            </div>
            <div class="form-group row m-3">
                <label for="lgFormGroupInput" class="col-sm-2 col-form-label col-form-label-lg text-dark">邮箱:</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control form-control-lg" name="account" placeholder="email">
                </div>
            </div>
            <div class="form-group row m-3">
                <label for="smFormGroupInput" class="col-sm-2 col-form-label col-form-label-lg text-dark">密码:</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control form-control-lg" name="password" placeholder="password">
                </div>
            </div>
            <div class="d-flex justify-content-center">
                <input type="submit" value="register" class="btn text-light bg-primary m-2">
            </div>
        </form>
    </div>
{% endblock %}